[package]
name = "nyandev/hybrid-ecs"
description = "Object oriented ECS library for Roblox"
version = "4.0.0"
license = "MIT"
authors = [
    "NyandogT9"
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "build.rbxm",
    "build.rbxl",
    "build.rbxlx",
    "build.rbxl.lock",
    "build.rbxlx.lock",
    ".vscode",
    "tests"
]

[dev-dependencies]
testez = "roblox/testez@0.4.1"